### ISSUE TITLE
Failed to load the theme-roulette package

### ISSUE THREAD

**Issue by hjoseph96** [DavidLGoldberg/theme-roulette#10]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.9.5
**Thrown From**: [theme-roulette](https://github.com/davidlgoldberg/theme-roulette) package, v1.1.0
### Stack Trace

Failed to load the theme-roulette package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/herbertjoseph/.atom/packages/theme-roulette/lib/theme-roulette-view.coffee:4:199)
    at /Users/herbertjoseph/.atom/packages/theme-roulette/lib/theme-roulette-view.coffee:13:5
    at Object.<anonymous> (/Users/herbertjoseph/.atom/packages/theme-roulette/lib/theme-roulette-view.coffee:120:5)
    at Object.<anonymous> (/Users/herbertjoseph/.atom/packages/theme-roulette/lib/theme-roulette-view.coffee:122:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "minimap"
    ],
    "themes": [
      "seti-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-handlebars, v1.0.0
auto-indent, v0.5.0
auto-update-packages, v1.0.0
autoclose-html, v0.18.0
autocomplete-paths, v1.0.2
better-handlebars, v0.1.1
emmet, v2.3.12
highlight-line, v0.11.0
iTunes, v0.2.0
jshint, v1.3.9
language-haml, v0.21.0
seti-ui, v0.7.1
theme-roulette, v1.1.0
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by DavidLGoldberg** [comment]
Yup, this package needs to be completely reworked.  Changes to Atom architecture etc.  Thanks for downloading though.  I might be fixing it this weekend actually.
